version: '3.8'
services:
  server:
    build: ./server
    ports:
      - "3000:3000"
    restart: always

  admin:
    build: ./admin
    ports:
      - "8080:8080"
    restart: always

  client:
    build: ./client
    ports:
      - "8081:8081"
    restart: always
